version: '3.3'

services:

    loadbalancer:
        build:
            context: ./loadBalancer
            dockerfile: Dockerfile
        container_name: loadbalancer
        ports: 
            - 80:80
        depends_on:
        - web
        - web2
        - web3    
    web:
        build:
            context: ./laboratorioVirtualizacionAYGO
            dockerfile: Dockerfile
        container_name: web
        ports: 
            - 35001:8080
    web2:
        build:
            context: ./laboratorioVirtualizacionAYGO
            dockerfile: Dockerfile
        container_name: web2
        ports: 
            - 35002:8080
    web3:
        build:
            context: ./laboratorioVirtualizacionAYGO
            dockerfile: Dockerfile
        container_name: web3
        ports: 
            - 35003:8080
            
    db:
        image: mongo:3.6.1
        container_name: db_mongo
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod   
        
volumes:
    mongodb:
    mongodb_config: 